# Generated by Django 5.0.14 on 2026-07-31 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('preferred_min_score', models.IntegerField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_requirements', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='company_requirements', to='skills.skillcategory')),
            ],
        ),
    ]
