# Generated by Django 5.0.14 on 2026-09-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_testattempt_project_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_score', models.IntegerField(default=0)),
                ('radar_data', models.JSONField(default=list)),
                ('gap_analysis', models.JSONField(default=list)),
                ('roadmap', models.JSONField(default=list)),
                ('strongest_skill', models.JSONField(blank=True, null=True)),
                ('weakest_skill', models.JSONField(blank=True, null=True)),
                ('scoring_method', models.CharField(default='ai', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
