# Generated by Django 5.0.14 on 2026-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
