# Generated by Django 5.0.14 on 2026-08-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltest',
            name='test_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('communication', 'Communication'), ('screen_task', 'Screen Task'), ('practical', 'Practical Project')], max_length=20),
        ),
    ]
