# Generated by Django 5.0.14 on 2026-07-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillscore',
            name='scoring_method',
            field=models.CharField(default='ai', max_length=20),
        ),
    ]
