# Generated by Django 5.0.14 on 2026-07-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_skillscore_scoring_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillscore',
            name='cheating_flags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
