# Generated by Django 5.0.14 on 2026-08-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_skillscore_cheating_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='project_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
