# Generated by Django 5.0.14 on 2026-07-26 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.skillscore')),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='skills.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
